version: "3"

services:
  php:
    image: php:7.2-cli
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/entrypoint.sh:/entrypoint.sh
    env_file: .env

  db:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
